### ISSUE TITLE
This repository not hacktoberfest as it does not follow the values of the event

### ISSUE THREAD

**Issue by jackson-roberio** [fineanmol/hacktoberfest#441]
My PR was received this way by the event:

![image](https://user-images.githubusercontent.com/3946126/193598885-c1143538-623c-4704-b81f-6e60907c9010.png)

**Comment by MayankUghade** [comment]
same bro

**Comment by MayankUghade** [comment]
@fineanmol pleas help with the problem.

**Comment by fineanmol** [comment]
@jackson-roberio @MayankUghade Yes, few contributors didn't liked the way we were trying to help new contributors so they have reported this repo. 
Now nothing can be done from my end.

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.
