### ISSUE TITLE
NO Repo suitable for hacktoberfest

### ISSUE THREAD

**Issue by GeraAlcantara** [fineanmol/hacktoberfest#487]
🐞 **Problem**
hacktoberfest mark this issue as excluded
🎯 **Goal**
make PR that are sutible in the guildline of hacktoberfest
this how it look on my profile 

![image](https://user-images.githubusercontent.com/32178037/193709633-85d37585-72c4-4e39-a71a-b7316fdb603a.png)

💡 **Possible solutions**
review the hacktoberfest guid lines

📋  **Steps to solve the problem**

*   hacktoberfest guid lines

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.
